project:
  type: website

website:
  title: "Community Shared Resources"
  navbar:
    logo: "images/mlx_logo_horizontal.png"
    #left:
    #  - href: index.qmd
    #    text: Home
    #  - about.qmd
    tools:
      - icon: github
        href: https://github.com/UW-Madison-DataScience/ML-X-Community
  sidebar:
    collapse-level: 1
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

